name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install root dependencies
        run: npm install

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Lint client
        run: |
          cd client
          npm run lint

      - name: Lint server
        run: |
          cd server
          npm run lint

      - name: Build frontend
        run: |
          cd client
          npm run build

      - name: Run backend tests
        run: |
          cd server
          npm test

      - name: Start backend
        run: |
          cd server
          NODE_ENV=test node index.js &

      - name: Start frontend
        run: |
          cd client
          npm run dev -- --host 0.0.0.0 &

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm test

    deploy:
      needs: [build_and_test]
      runs-on: ubuntu-latest
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_release:
    needs: [build_and_test, deploy]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v6

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  notification-discord: 
    needs: [build_and_test, deploy]
    if: always()
    runs-on: ubuntu latest
    steps: 
      - uses: actions/checkout@v6

      - name: Discord notification(success)
        if: ${{ success() }}
        uses: Ilshidur/action-discord@master
        with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{job.status}}
        title: "Deployment succeeded"
        description: "A new version was deployed"

      - name: Discord notification(failure)
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@master
        with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{job.status}}
        title: "Build failed"
        description: "Commit ${{ github.sha }} by ${{ github.actor }} broke the build. See: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"